// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBSVSYzZAyUTxB0615pNWCi5ZbgJ81H8',
    appId: '1:1080667745634:web:293fc9a1c4fd677206103b',
    messagingSenderId: '1080667745634',
    projectId: 'perlinda-36519',
    authDomain: 'perlinda-36519.firebaseapp.com',
    storageBucket: 'perlinda-36519.appspot.com',
    measurementId: 'G-SFSS4DCVZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRjz_puZLjRFW7hjncHcvrEgSq77SOzE',
    appId: '1:1080667745634:android:3d67cdc730374f7406103b',
    messagingSenderId: '1080667745634',
    projectId: 'perlinda-36519',
    storageBucket: 'perlinda-36519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8V7x6OcQHqoo1K96_phnyiEwV19KntQc',
    appId: '1:1080667745634:ios:71f3399118c84b2a06103b',
    messagingSenderId: '1080667745634',
    projectId: 'perlinda-36519',
    storageBucket: 'perlinda-36519.appspot.com',
    iosBundleId: 'com.example.flutterPerlindaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8V7x6OcQHqoo1K96_phnyiEwV19KntQc',
    appId: '1:1080667745634:ios:71f3399118c84b2a06103b',
    messagingSenderId: '1080667745634',
    projectId: 'perlinda-36519',
    storageBucket: 'perlinda-36519.appspot.com',
    iosBundleId: 'com.example.flutterPerlindaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuBSVSYzZAyUTxB0615pNWCi5ZbgJ81H8',
    appId: '1:1080667745634:web:e7657301b695dd8306103b',
    messagingSenderId: '1080667745634',
    projectId: 'perlinda-36519',
    authDomain: 'perlinda-36519.firebaseapp.com',
    storageBucket: 'perlinda-36519.appspot.com',
    measurementId: 'G-W1NERTM9YN',
  );
}
